/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radionica.UI;

import ERS.queries.ERSQuery;
import JFXChartGenerators.CssStyles.CSSStyles;
import JFXChartGenerators.StackedBars.AbstractCategory_StackedBarGenerator;
import JFXChartGenerators.StackedBars.StackedBarCategoryX_Generator;
import com.dobrivoje.utilities.warnings.Display;
import ent.Firma;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//radionica.UI//DnevniTimeLine//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "DnevniTimeLineTopComponent",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "radionica.UI.DnevniTimeLineTopComponent")
@ActionReference(path = "Menu/Window/Servis", position = 1300)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DnevniTimeLineAction",
        preferredID = "DnevniTimeLineTopComponent"
)
@Messages({
    "CTL_DnevniTimeLineAction=Dnevni TimeLine",
    "CTL_DnevniTimeLineTopComponent=Dnevni TimeLine",
    "HINT_DnevniTimeLineTopComponent=Dnevni TimeLine"
})
public final class DnevniTimeLineTopComponent extends TopComponent {

    private Lookup.Result<String> kalendarLookup;
    private LookupListener llKalendar;
    private Lookup.Result<Firma> firmaLookup;
    private LookupListener llFirma;

    private final AbstractCategory_StackedBarGenerator radniciFXCategories = new StackedBarCategoryX_Generator();

    //<editor-fold defaultstate="collapsed" desc="Kalendar Bind">
    private String kalendarDatum_bind;
    private boolean kalendarIzmenjen;
    
    public String getKalendarDatum() {
        return kalendarDatum_bind;
    }

    public void setKalendarDatum(String kalendar) {
        if (kalendar == null) {
            kalendar = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            kalendarIzmenjen = true;
        }
        if (!kalendar.equals(this.kalendarDatum_bind)) {
            this.kalendarDatum_bind = kalendar;
            this.kalendarIzmenjen = true;
        } else {
            this.kalendarIzmenjen = false;
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Firma bind">
    private Firma firma_bind = null;
    private boolean firmaIzmenjena;

    public Firma getFirma_bind() {
        return firma_bind;
    }

    public void setFirma(Firma firma_bind) {
        if (firma_bind == null) {
            this.firma_bind = ERSQuery.FirmaID(2);
            this.firmaIzmenjena = true;
        }
        if (!firma_bind.equals(this.firma_bind)) {
            this.firma_bind = firma_bind;
            this.firmaIzmenjena = true;
        } else {
            this.firmaIzmenjena = false;
        }
    }
    //</editor-fold>

    public DnevniTimeLineTopComponent() {
        initComponents();
        setName(Bundle.CTL_DnevniTimeLineTopComponent());
        setToolTipText(Bundle.HINT_DnevniTimeLineTopComponent());

        // Print funkcionalnost
        putClientProperty("print.printable", Boolean.TRUE);

        setKalendarDatum(null);
        setFirma(null);

        radniciFXCategories.setUpChartPanel(jPanel_TimeLine);
        radniciFXCategories.setCSSStyle(CSSStyles.Style.RED_BAR);
        setFX_TimeLine(firma_bind, "2014-4-9", radniciFXCategories);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_TimeLine = new javax.swing.JPanel();

        jPanel_TimeLine.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_TimeLine.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_TimeLine, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_TimeLine, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_TimeLine;
    // End of variables declaration//GEN-END:variables
    //<editor-fold defaultstate="collapsed" desc="UI Lookup">
    @Override
    public void componentOpened() {
        kalendarLookup = WindowManager
                .getDefault()
                .findTopComponent("PretrazivacTopComponent")
                .getLookup().lookupResult(String.class);
        firmaLookup = WindowManager
                .getDefault()
                .findTopComponent("PretrazivacTopComponent")
                .getLookup().lookupResult(Firma.class);

        llKalendar = new LookupListener() {
            @Override
            public void resultChanged(LookupEvent le) {
                Lookup.Result lr = (Lookup.Result) le.getSource();
                Collection<String> datumi = lr.allInstances();

                if (!datumi.isEmpty()) {
                    for (String d1 : datumi) {
                        setKalendarDatum(d1);
                        setFX_TimeLine(firma_bind, d1, radniciFXCategories);
                    }
                }
            }
        };
        kalendarLookup.addLookupListener(llKalendar);

        llFirma = new LookupListener() {
            @Override
            public void resultChanged(LookupEvent le) {
                Lookup.Result lr = (Lookup.Result) le.getSource();
                Collection<Firma> firme = lr.allInstances();

                if (!firme.isEmpty()) {
                    for (Firma f1 : firme) {
                        setFirma(f1);
                        setFX_TimeLine(firma_bind, kalendarDatum_bind, radniciFXCategories);
                    }
                }
            }
        };
        firmaLookup.addLookupListener(llKalendar);
    }

    @Override
    public void componentClosed() {
        kalendarLookup.removeLookupListener(llKalendar);
        kalendarLookup = null;
        firmaLookup.removeLookupListener(llFirma);
        firmaLookup = null;
    }
     //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="ne treba...">
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    //</editor-fold>

    private void setFX_TimeLine(Firma Firma, String Datum, AbstractCategory_StackedBarGenerator asbg) {
        if (kalendarIzmenjen || firmaIzmenjena) {
            try {
                /*
                 asbg.setUpSeries(ERS.queries.ERSQuery.allWorkersTimeLine(firma, Datum));

                 asbg.setChartTitle("Učešće Servisnih Savetnika," + SrpskiKalendar.getMesecNazivLatinica(Mesec) + " " + String.valueOf(Godina));
                 asbg.setSeriesTitles("Radovi", "Materijal");
                 asbg.createFXObject();
                    
                 */
            } catch (NullPointerException ex) {
                Display.obavestenjeBaloncic("Greška.", ex.getLocalizedMessage(), Display.TIP_OBAVESTENJA.GRESKA);
            } catch (Exception e) {
                Display.obavestenjeBaloncic("Greška.", e.toString(), Display.TIP_OBAVESTENJA.GRESKA);
            }
        }
    }
}
