/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package servis.manager.izvestaji.UI;

import com.dobrivoje.utilities.datumi.DatumSelektor;
import com.dobrivoje.utilities.warnings.Display;
import ent.Orgjed;
import izvestaji.resursi.generatori.ReportGenerator;
import java.util.Collection;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//UI//IzvestajiOrgJed//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "IzvestajiOrgJedTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false, position = 1200)
@ActionID(category = "Window", id = "UI.IzvestajiOrgJedTopComponent")
@ActionReference(path = "Menu/Izveštaji", position = 2000)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_IzvestajiOrgJedAction",
        preferredID = "IzvestajiOrgJedTopComponent")
@Messages({
    "CTL_IzvestajiOrgJedAction=Izveštaji za Org. Jedinicu",
    "CTL_IzvestajiOrgJedTopComponent=Izveštaji za Org. Jedinicu",
    "HINT_IzvestajiOrgJedTopComponent=Izveštaji za Org. Jedinicu"
})
public final class IzvestajiOrgJedTopComponent extends TopComponent
        implements LookupListener {

    private Lookup.Result<Orgjed> odabranaOrgJed;
    private Lookup.Result<DatumSelektor> odabraniDatumi;
    //
    private Orgjed orgjedLookup;
    private DatumSelektor ds;

    public IzvestajiOrgJedTopComponent() {
        initComponents();
        setName(Bundle.CTL_IzvestajiOrgJedTopComponent());
        setToolTipText(Bundle.HINT_IzvestajiOrgJedTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topComponent1 = new org.openide.windows.TopComponent();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_KOMPANIJA = new javax.swing.JTextField();
        jTextField_FIRMA = new javax.swing.JTextField();
        jTextField_ORGJED = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField_DATUMOD = new javax.swing.JTextField();
        jTextField_DATUMDO = new javax.swing.JTextField();
        jButton_Produktivnost_ZaPeriodu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jTextField_KOMPANIJA.setEditable(false);
        jTextField_KOMPANIJA.setText(org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jTextField_KOMPANIJA.text")); // NOI18N

        jTextField_FIRMA.setEditable(false);
        jTextField_FIRMA.setText(org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jTextField_FIRMA.text")); // NOI18N

        jTextField_ORGJED.setEditable(false);
        jTextField_ORGJED.setText(org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jTextField_ORGJED.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jLabel7.text")); // NOI18N

        jTextField_DATUMOD.setEditable(false);
        jTextField_DATUMOD.setText(org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jTextField_DATUMOD.text")); // NOI18N

        jTextField_DATUMDO.setEditable(false);
        jTextField_DATUMDO.setText(org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jTextField_DATUMDO.text")); // NOI18N

        javax.swing.GroupLayout topComponent1Layout = new javax.swing.GroupLayout(topComponent1);
        topComponent1.setLayout(topComponent1Layout);
        topComponent1Layout.setHorizontalGroup(
            topComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topComponent1Layout.createSequentialGroup()
                .addGroup(topComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DATUMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DATUMDO, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topComponent1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(topComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(topComponent1Layout.createSequentialGroup()
                            .addComponent(jTextField_KOMPANIJA, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_FIRMA))
                        .addComponent(jTextField_ORGJED, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topComponent1Layout.setVerticalGroup(
            topComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topComponent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_KOMPANIJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_FIRMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ORGJED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_DATUMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jTextField_DATUMDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(jButton_Produktivnost_ZaPeriodu, org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jButton_Produktivnost_ZaPeriodu.text")); // NOI18N
        jButton_Produktivnost_ZaPeriodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Produktivnost_ZaPerioduActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(IzvestajiOrgJedTopComponent.class, "IzvestajiOrgJedTopComponent.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator5)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator4)
                        .addComponent(topComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE))
                    .addComponent(jButton_Produktivnost_ZaPeriodu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(topComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jButton_Produktivnost_ZaPeriodu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Produktivnost_ZaPerioduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Produktivnost_ZaPerioduActionPerformed
        try {
            new ReportGenerator()
                    .generisanjeIzvestaja_ORGJED(
                            orgjedLookup.getIDOrgjed(),
                            ds.getYMDDatumOD(),
                            ds.getYMDDatumDO());

        } catch (NullPointerException npe) {
            Display.obavestenjeBaloncic("Greška.", "Izabrati Org. Jedinicu i Datume.", Display.TIP_OBAVESTENJA.GRESKA);
        } catch (Exception e) {
            Display.obavestenjeBaloncic("Greška.", e.getMessage(), Display.TIP_OBAVESTENJA.GRESKA);
        }
    }//GEN-LAST:event_jButton_Produktivnost_ZaPerioduActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Produktivnost_ZaPeriodu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField_DATUMDO;
    private javax.swing.JTextField jTextField_DATUMOD;
    private javax.swing.JTextField jTextField_FIRMA;
    private javax.swing.JTextField jTextField_KOMPANIJA;
    private javax.swing.JTextField jTextField_ORGJED;
    private org.openide.windows.TopComponent topComponent1;
    // End of variables declaration//GEN-END:variables

    //<editor-fold defaultstate="collapsed" desc="Utils lookup">
    @Override
    public void componentOpened() {
        odabranaOrgJed = Utilities
                .actionsGlobalContext()
                .lookupResult(Orgjed.class);

        LookupListener ll1 = new LookupListener() {
            @Override
            public void resultChanged(LookupEvent le) {

                Lookup.Result lroj = (Lookup.Result) le.getSource();
                Collection<Orgjed> orgJedinice = lroj.allInstances();

                if (!orgJedinice.isEmpty()) {
                    for (Orgjed oj : orgJedinice) {
                        //orgjedLookup = (Orgjed) oj;
                        orgjedLookup = oj;

                        jTextField_KOMPANIJA.setText(orgjedLookup.getFKIDFirma().getFkIdk().getNazivKompanije());
                        jTextField_FIRMA.setText(orgjedLookup.getFKIDFirma().getNaziv());
                        jTextField_ORGJED.setText(orgjedLookup.getNaziv());
                    }
                }
            }
        };
        odabranaOrgJed.addLookupListener(ll1);
        ll1.resultChanged(new LookupEvent(odabranaOrgJed));

        odabraniDatumi = Utilities
                .actionsGlobalContext()
                .lookupResult(DatumSelektor.class);

        LookupListener ll2 = new LookupListener() {
            @Override
            public void resultChanged(LookupEvent le) {
                Lookup.Result lrds = (Lookup.Result) le.getSource();
                Collection<DatumSelektor> datumi = lrds.allInstances();
                if (!datumi.isEmpty()) {
                    for (DatumSelektor ds1 : datumi) {
                        //ds = (DatumSelektor) ds1;
                        ds = ds1;
                        jTextField_DATUMOD.setText(ds.getYMDDatumOD());
                        jTextField_DATUMDO.setText(ds.getYMDDatumDO());
                    }
                }
            }
        };
        odabraniDatumi.addLookupListener(ll2);
        ll2.resultChanged(new LookupEvent(odabraniDatumi));
    }

    @Override
    public void componentClosed() {
        odabranaOrgJed.removeLookupListener(this);
        odabranaOrgJed = null;

        odabraniDatumi.removeLookupListener(this);
        odabraniDatumi = null;
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="ne treba">
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void resultChanged(LookupEvent le) {
        throw new UnsupportedOperationException();
    }
    //</editor-fold>
}
