/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package servis.manager.izvestaji.UI;

import com.dobrivoje.utilities.datumi.DatumSelektor;
import com.dobrivoje.utilities.warnings.Display;
import ent.Firma;
import izvestaji.resursi.generatori.ReportGenerator;
import java.util.Collection;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//UI//IzvestajiFirma//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "IzvestajiFirmaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false, position = 1300)
@ActionID(category = "Window", id = "UI.IzvestajiFirmaTopComponent")
@ActionReference(path = "Menu/Izveštaji", position = 1000)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_IzvestajiFirmaAction",
        preferredID = "IzvestajiFirmaTopComponent")
@Messages({
    "CTL_IzvestajiFirmaAction=Izveštaji za Firmu",
    "CTL_IzvestajiFirmaTopComponent=Izveštaji za Firmu",
    "HINT_IzvestajiFirmaTopComponent=Izveštaji za Firmu"
})
public final class IzvestajiFirmaTopComponent extends TopComponent
        implements LookupListener {

    private Lookup.Result<Firma> firmaLookup;
    private Lookup.Result<DatumSelektor> datumiLookup;
    //
    private Firma firma;
    private DatumSelektor ds;
    //
    private ReportGenerator reportGenerator;

    public IzvestajiFirmaTopComponent() {
        initComponents();
        setName(Bundle.CTL_IzvestajiFirmaTopComponent());
        setToolTipText(Bundle.HINT_IzvestajiFirmaTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup_Efikasnost = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jTextField_KOMPANIJA = new javax.swing.JTextField();
        jTextField_FIRMA = new javax.swing.JTextField();
        jTextField_DATUMOD = new javax.swing.JTextField();
        jTextField_GodinaOD = new javax.swing.JTextField();
        jTextField_DATUMDO = new javax.swing.JTextField();
        jTextField_GodinaDO = new javax.swing.JTextField();
        jCheckBox_AKTIVNI_RADNICI = new javax.swing.JCheckBox();
        jCheckBox_NEAKTIVNI_RADNICI = new javax.swing.JCheckBox();
        jCheckBox_SAMO_RADNICI = new javax.swing.JCheckBox();
        jCheckBox_OSTALI_NALOZI = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel_Klijent = new javax.swing.JPanel();
        jRadioButton_Efikasnost_ElektroMehanika = new javax.swing.JRadioButton();
        jRadioButton_Efikasnost_Limarija = new javax.swing.JRadioButton();
        jRadioButton_Efikasnost_SveJedinice = new javax.swing.JRadioButton();
        jButton_Efikasnost_Servisa_Izvestaj = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jLabel4.text")); // NOI18N

        jTextField_KOMPANIJA.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${kompanija_bind.nazivKompanije}"), jTextField_KOMPANIJA, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField_FIRMA.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${firma_bind.naziv}"), jTextField_FIRMA, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextField_DATUMOD.setEditable(false);
        jTextField_DATUMOD.setText(org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jTextField_DATUMOD.text")); // NOI18N

        jTextField_GodinaOD.setEditable(false);
        jTextField_GodinaOD.setText(org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jTextField_GodinaOD.text")); // NOI18N

        jTextField_DATUMDO.setEditable(false);
        jTextField_DATUMDO.setText(org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jTextField_DATUMDO.text")); // NOI18N

        jTextField_GodinaDO.setEditable(false);
        jTextField_GodinaDO.setText(org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jTextField_GodinaDO.text")); // NOI18N

        jCheckBox_AKTIVNI_RADNICI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_AKTIVNI_RADNICI.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox_AKTIVNI_RADNICI, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jCheckBox_AKTIVNI_RADNICI.text")); // NOI18N

        jCheckBox_NEAKTIVNI_RADNICI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_NEAKTIVNI_RADNICI.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox_NEAKTIVNI_RADNICI, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jCheckBox_NEAKTIVNI_RADNICI.text")); // NOI18N

        jCheckBox_SAMO_RADNICI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_SAMO_RADNICI.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox_SAMO_RADNICI, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jCheckBox_SAMO_RADNICI.text")); // NOI18N

        jCheckBox_OSTALI_NALOZI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_OSTALI_NALOZI.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox_OSTALI_NALOZI, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jCheckBox_OSTALI_NALOZI.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jLabel8.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jLabel7.text_1")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jLabel10.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jLabel9.text")); // NOI18N

        jPanel_Klijent.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jPanel_Klijent.border.title"))); // NOI18N

        buttonGroup_Efikasnost.add(jRadioButton_Efikasnost_ElektroMehanika);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton_Efikasnost_ElektroMehanika, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jRadioButton_Efikasnost_ElektroMehanika.text")); // NOI18N

        buttonGroup_Efikasnost.add(jRadioButton_Efikasnost_Limarija);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton_Efikasnost_Limarija, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jRadioButton_Efikasnost_Limarija.text")); // NOI18N

        buttonGroup_Efikasnost.add(jRadioButton_Efikasnost_SveJedinice);
        jRadioButton_Efikasnost_SveJedinice.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton_Efikasnost_SveJedinice, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jRadioButton_Efikasnost_SveJedinice.text")); // NOI18N

        javax.swing.GroupLayout jPanel_KlijentLayout = new javax.swing.GroupLayout(jPanel_Klijent);
        jPanel_Klijent.setLayout(jPanel_KlijentLayout);
        jPanel_KlijentLayout.setHorizontalGroup(
            jPanel_KlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KlijentLayout.createSequentialGroup()
                .addGroup(jPanel_KlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_Efikasnost_Limarija)
                    .addComponent(jRadioButton_Efikasnost_SveJedinice)
                    .addComponent(jRadioButton_Efikasnost_ElektroMehanika))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel_KlijentLayout.setVerticalGroup(
            jPanel_KlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KlijentLayout.createSequentialGroup()
                .addComponent(jRadioButton_Efikasnost_SveJedinice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Efikasnost_ElektroMehanika, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Efikasnost_Limarija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(jButton_Efikasnost_Servisa_Izvestaj, org.openide.util.NbBundle.getMessage(IzvestajiFirmaTopComponent.class, "IzvestajiFirmaTopComponent.jButton_Efikasnost_Servisa_Izvestaj.text")); // NOI18N
        jButton_Efikasnost_Servisa_Izvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Efikasnost_Servisa_IzvestajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_DATUMDO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_DATUMOD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_GodinaOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_GodinaDO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox_AKTIVNI_RADNICI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_NEAKTIVNI_RADNICI)
                                .addGap(17, 17, 17))
                            .addComponent(jCheckBox_SAMO_RADNICI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Efikasnost_Servisa_Izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBox_OSTALI_NALOZI))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_KOMPANIJA, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_FIRMA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel_Klijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_KOMPANIJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_FIRMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_DATUMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_GodinaOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_DATUMDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_GodinaDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_AKTIVNI_RADNICI)
                            .addComponent(jCheckBox_NEAKTIVNI_RADNICI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_SAMO_RADNICI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_OSTALI_NALOZI)))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Klijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Efikasnost_Servisa_Izvestaj)
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Efikasnost_Servisa_IzvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Efikasnost_Servisa_IzvestajActionPerformed
        // TODO add your handling code here:

        if (jRadioButton_Efikasnost_SveJedinice.isSelected()) {
            try {

                new ReportGenerator()
                        .generisanjeIzvestaja_EfikasnostServisa(ds.getYMDDatumOD(),
                                ds.getYMDDatumDO(),
                                jCheckBox_SAMO_RADNICI.isSelected(),
                                jCheckBox_OSTALI_NALOZI.isSelected(),
                                firma.getIDFirma());

            } catch (NullPointerException npe) {
                Display.obavestenjeBaloncic("Greška.", "Izabrati firmu i datume.", Display.TIP_OBAVESTENJA.GRESKA);
            } catch (Exception e) {
                Display.obavestenjeBaloncic("Greška.", e.getMessage(), Display.TIP_OBAVESTENJA.GRESKA);
            }
        } else if (jRadioButton_Efikasnost_ElektroMehanika.isSelected()) {
            try {
                new ReportGenerator()
                        .generisanjeIzvestaja_EfikasnostServisa_MehLim(
                                ds.getYMDDatumOD(),
                                ds.getYMDDatumDO(),
                                jCheckBox_SAMO_RADNICI.isSelected(),
                                jCheckBox_OSTALI_NALOZI.isSelected(),
                                firma.getIDFirma(),
                                true);

            } catch (NullPointerException npe) {
                Display.obavestenjeBaloncic("Greška.", "Izabrati firmu i datume.", Display.TIP_OBAVESTENJA.GRESKA);
            } catch (Exception e) {
                Display.obavestenjeBaloncic("Greška.", e.getMessage(), Display.TIP_OBAVESTENJA.GRESKA);
            }
        } else if (jRadioButton_Efikasnost_Limarija.isSelected()) {
            try {
                new ReportGenerator()
                        .generisanjeIzvestaja_EfikasnostServisa_MehLim(
                                ds.getYMDDatumOD(),
                                ds.getYMDDatumDO(),
                                jCheckBox_SAMO_RADNICI.isSelected(),
                                jCheckBox_OSTALI_NALOZI.isSelected(),
                                firma.getIDFirma(),
                                false);

            } catch (NullPointerException npe) {
                Display.obavestenjeBaloncic("Greška.", "Izabrati firmu i datume.", Display.TIP_OBAVESTENJA.GRESKA);
            } catch (Exception e) {
                Display.obavestenjeBaloncic("Greška.", e.getMessage(), Display.TIP_OBAVESTENJA.GRESKA);
            }
        }
    }//GEN-LAST:event_jButton_Efikasnost_Servisa_IzvestajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Efikasnost;
    private javax.swing.JButton jButton_Efikasnost_Servisa_Izvestaj;
    private javax.swing.JCheckBox jCheckBox_AKTIVNI_RADNICI;
    private javax.swing.JCheckBox jCheckBox_NEAKTIVNI_RADNICI;
    private javax.swing.JCheckBox jCheckBox_OSTALI_NALOZI;
    private javax.swing.JCheckBox jCheckBox_SAMO_RADNICI;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_Klijent;
    private javax.swing.JRadioButton jRadioButton_Efikasnost_ElektroMehanika;
    private javax.swing.JRadioButton jRadioButton_Efikasnost_Limarija;
    private javax.swing.JRadioButton jRadioButton_Efikasnost_SveJedinice;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField_DATUMDO;
    private javax.swing.JTextField jTextField_DATUMOD;
    private javax.swing.JTextField jTextField_FIRMA;
    private javax.swing.JTextField jTextField_GodinaDO;
    private javax.swing.JTextField jTextField_GodinaOD;
    private javax.swing.JTextField jTextField_KOMPANIJA;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //<editor-fold defaultstate="collapsed" desc="Lookup Utils">
    @Override
    public void componentOpened() {
        firmaLookup = Utilities
                .actionsGlobalContext()
                .lookupResult(Firma.class);

        firmaLookup.addLookupListener(new LookupListener() {
            @Override
            public void resultChanged(LookupEvent le) {
                Lookup.Result lr = (Lookup.Result) le.getSource();
                Collection<Firma> firme = lr.allInstances();

                if (!firme.isEmpty()) {
                    for (Firma f1 : firme) {
                        jTextField_KOMPANIJA.setText(f1.getFkIdk().getNazivKompanije());
                        jTextField_FIRMA.setText(f1.getNaziv());

                        firma = f1;
                    }
                }
            }
        });

        datumiLookup = Utilities
                .actionsGlobalContext()
                .lookupResult(DatumSelektor.class);

        datumiLookup.addLookupListener(new LookupListener() {
            @Override
            public void resultChanged(LookupEvent le) {
                Lookup.Result lr = (Lookup.Result) le.getSource();
                Collection<DatumSelektor> datumi = lr.allInstances();

                if (!datumi.isEmpty()) {
                    for (DatumSelektor d1 : datumi) {
                        jTextField_DATUMOD.setText(d1.getYMDDatumOD());
                        jTextField_DATUMDO.setText(d1.getYMDDatumDO());

                        jTextField_GodinaOD.setText(Integer.toString(d1.getGodinaOD()));
                        jTextField_GodinaDO.setText(Integer.toString(d1.getGodinaDO()));

                        ds = d1;
                    }
                }
            }
        });
    }

    @Override
    public void componentClosed() {
        firmaLookup.removeLookupListener(this);
        firmaLookup = null;

        datumiLookup.removeLookupListener(this);
        datumiLookup = null;
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Ne treba">
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void resultChanged(LookupEvent le) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //</editor-fold>
}
